WayBillAct provider
evotor/egais-api pull request #9
Opened 2018-03-28 13:54 UTC by remiel-undead

2018-03-28 14:28 UTC, xcam commented on api/src/main/java/ru/evotor/egais/api/provider/waybillact/WayBillActContract.kt
> +     * Уникальный идентификатор акта
не то описание

2018-03-28 14:29 UTC, xcam commented on api/src/main/java/ru/evotor/egais/api/provider/waybillact/WayBillActContract.kt
> +     * Тип приемки: Полная/частичная
тип подтверждения не определяет теперь тип приемки?

2018-03-28 14:29 UTC, xcam commented on api/src/main/java/ru/evotor/egais/api/provider/waybillact/WayBillActPositionContract.kt
> -     * Регистрационный номер раздела справки 2.
справки 2 правильно. Справка Б - это старое название

2018-03-28 14:31 UTC, xcam requested changes
см комментарии

2018-03-28 15:55 UTC, remiel-undead commented on api/src/main/java/ru/evotor/egais/api/provider/waybillact/WayBillActPositionContract.kt
> -     * Регистрационный номер раздела справки 2.
`+`

2018-03-28 15:55 UTC, remiel-undead commented on api/src/main/java/ru/evotor/egais/api/provider/waybillact/WayBillActContract.kt
> +     * Уникальный идентификатор акта
`+`

2018-03-28 15:56 UTC, remiel-undead commented on api/src/main/java/ru/evotor/egais/api/provider/waybillact/WayBillActContract.kt
> +     * Тип приемки: Полная/частичная
если принимаем/отказываем, то полная, а если есть расхождения, то частичная?

2018-03-29 08:49 UTC, xcam requested changes

2018-03-29 08:49 UTC, xcam commented on api/src/main/java/ru/evotor/egais/api/provider/waybillact/WayBillActContract.kt
> +     * Тип приемки: Полная/частичная
\+

2018-03-29 09:18 UTC, remiel-undead commented on api/src/main/java/ru/evotor/egais/api/provider/waybillact/WayBillActContract.kt
> +     * Тип приемки: Полная/частичная
оставляем поле тип приемки, т.к. для первой версии протокола нет типа подтверждения "есть расхождения"(только принимаем/отказываем) , и тип приемки может быть как полный, так и частичный

2018-03-29 10:31 UTC, merged